#!/usr/bin/env bash
#SBATCH --job-name=e2e_csv_stats
#SBATCH --nodes=1
#SBATCH --ntasks=2
#SBATCH --cpus-per-task=4
#SBATCH --time=0:10:00
#SBATCH --output=tests/e2e/slurm-%j.out
#SBATCH --error=tests/e2e/slurm-%j.err

# End-to-end validation: run the CSV stats orchestrator with three different
# rank/thread configurations and verify all outputs are byte-for-byte identical
# and match the expected output generated by gen_test_data.py.
set -e

# Run from repo root regardless of where the script is invoked from.
cd "$(dirname "$0")/../.."

# Generate test data and expected.txt (idempotent).
python3 tests/e2e/gen_test_data.py

# run <n_ranks> <cpus_per_task> <output_file>
# srun sets SLURM_CPUS_PER_TASK automatically from --cpus-per-task.
run() {
    local n="$1" cpus="$2" out="$3"
    srun -n "$n" --cpus-per-task="$cpus" \
        ./build/orchestrator --dir tests/e2e/data > "$out" 2>/dev/null
}

tmpdir=$(mktemp -d)
trap 'rm -rf "$tmpdir"' EXIT

# Three configurations: same data, different rank/thread splits.
# SLURM_CPUS_PER_TASK=1 is invalid on rank 0 (0 workers); minimum is 2.
run 1 2 "$tmpdir/out1.txt"   # 1 rank, 1 worker
run 1 4 "$tmpdir/out2.txt"   # 1 rank, 3 workers
run 2 4 "$tmpdir/out3.txt"   # 2 ranks, 7 workers total

fail=0

if ! diff -q "$tmpdir/out1.txt" "$tmpdir/out2.txt" > /dev/null; then
    echo "FAIL: out1 (n=1 cpus=2) != out2 (n=1 cpus=4)"
    diff "$tmpdir/out1.txt" "$tmpdir/out2.txt" || true
    fail=1
fi

if ! diff -q "$tmpdir/out1.txt" "$tmpdir/out3.txt" > /dev/null; then
    echo "FAIL: out1 (n=1 cpus=2) != out3 (n=2 cpus=4)"
    diff "$tmpdir/out1.txt" "$tmpdir/out3.txt" || true
    fail=1
fi

if ! diff -q "$tmpdir/out1.txt" tests/e2e/expected.txt > /dev/null; then
    echo "FAIL: out1 != tests/e2e/expected.txt"
    diff "$tmpdir/out1.txt" tests/e2e/expected.txt || true
    fail=1
fi

if [ "$fail" -eq 0 ]; then
    echo "PASS: all E2E outputs match"
    echo "---"
    cat "$tmpdir/out1.txt"
fi
exit "$fail"
